scraping:
  channels: []
  continuous_scraping: true
  download_media: true
  interval_seconds: 300
  message_limit: 100
telegram:
  api_hash: 3f1058f88dd6b84c3213873d3d929e44
  api_id: 27662776
  phone_number: '+5534996839044'
  session_file: session.session
